export const CHANNELS_LIST_ITEM_FETCH_DATA_SUCCESS = "CHANNELS_LIST_ITEM_FETCH_DATA_SUCCESS";
export const CHANNELS_FETCH_DATA_SUCCESS = "CHANNELS_FETCH_DATA_SUCCESS";
export const CHANNELS_LIST_FETCH_DATA_SUCCESS = "CHANNELS_LIST_FETCH_DATA_SUCCESS";